sudo: required
services:
  - docker

before_install:
  - docker build -t houssamlahrach/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true houssamlahrach/docker-react npm run test -- --coverage